// Fallback Pakistani news stories in case World News API is offline or quota reached
export const stories = [
  {
    id: 'story-1',
    kind: 'Business & Trade',
    source: 'DAWN',
    title: 'Local Automakers Voice Concerns as Imports of Used Cars Surge in September',
    text: 'Imports of used cars surged in September after easing of regulations, inviting criticism from local manufacturers while importers claim competition will benefit consumers.',
    time: '15 min ago',
    location: 'Islamabad, PK',
    author: 'Kalbe Ali',
    url: 'https://www.dawn.com',
  },
  {
    id: 'story-2',
    kind: 'Sports',
    source: 'THE NEWS',
    title: 'Asian Games Men’s Cricket Final: Pakistan Squad Prepares for Showdown',
    text: 'Pakistan heads into the final with a settled batting core and bowling lineup led by spinners aiming to exploit turn on the surface.',
    time: '45 min ago',
    location: 'Sports Desk',
    author: 'Sports Correspondent',
    url: 'https://www.thenews.com.pk',
  },
  {
    id: 'story-3',
    kind: 'Karachi Metro',
    source: 'EXPRESS TRIBUNE',
    title: 'Port Qasim & Marine Cargo Telemetry Reaches Record High in Third Quarter',
    text: 'Automated logistics systems report surging trade volume and automated clearance times at Pakistan’s key deep-water marine terminal.',
    time: '2 hours ago',
    location: 'Karachi, PK',
    author: 'Maritime Bureau',
    url: 'https://tribune.com.pk',
  },
  {
    id: 'story-4',
    kind: 'Politics',
    source: 'GEO NEWS',
    title: 'Federal Cabinet Evaluates Digital Governance & National IT Policy Roadmap',
    text: 'A high-level session reviewed broadband expansion, cloud data centers, and digital public infrastructure projects across Sindh and Punjab.',
    time: '3 hours ago',
    location: 'National Wire',
    author: 'Political Bureau',
    url: 'https://geo.tv',
  },
  {
    id: 'story-5',
    kind: 'Technology',
    source: 'DAWN',
    title: 'Pakistani Tech Startups See Renewed Influx in Regional Venture Funding',
    text: 'Fintech and AI logistics sectors lead the recovery as foreign investors resume capital allocations for enterprise software ventures.',
    time: '5 hours ago',
    location: 'Karachi Central',
    author: 'Technology Desk',
    url: 'https://www.dawn.com',
  },
  {
    id: 'story-6',
    kind: 'Karachi Metro',
    source: 'EXPRESS TRIBUNE',
    title: 'Sindh Urban Development Authority Announces Automated Traffic Grid Expansion',
    text: 'Smart signal nodes and computer-vision vehicle management slated for installation across 42 key metropolitan arteries in Karachi.',
    time: '7 hours ago',
    location: 'Karachi, PK',
    author: 'Civic Desk',
    url: 'https://tribune.com.pk',
  }
]
